### ISSUE TITLE
Unable to build locally using Maven

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/sonar-auth-openshift#2]
Attempted to run `mvn clean package` and ended up with errors on the Unit Test related to SSL:

```
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.583 s <<< FAILURE! - in com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest
[ERROR] failToInitWhenDisabled(com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest)  Time elapsed: 0.439 s  <<< ERROR!
java.lang.IllegalStateException: Problem setting up ssl
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)
Caused by: java.lang.NullPointerException
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)

[ERROR] init(com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest)  Time elapsed: 0.029 s  <<< ERROR!
java.lang.IllegalStateException: Problem setting up ssl
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)
Caused by: java.lang.NullPointerException
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)

[ERROR] checkFields(com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest)  Time elapsed: 0.03 s  <<< ERROR!
java.lang.IllegalStateException: Problem setting up ssl
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)
Caused by: java.lang.NullPointerException
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)

[ERROR] isEnabled(com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest)  Time elapsed: 0.028 s  <<< ERROR!
java.lang.IllegalStateException: Problem setting up ssl
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)
Caused by: java.lang.NullPointerException
        at com.rhc.sonarqube.auth.openshift.OpenShiftIdentityProviderTest.preTest(OpenShiftIdentityProviderTest.java:81)

[INFO] Running com.rhc.sonarqube.auth.openshift.AuthOpenShiftPluginTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.rhc.sonarqube.auth.openshift.AuthOpenShiftPluginTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OpenShiftIdentityProviderTest.preTest:81 » IllegalState Problem setting up ssl
[ERROR]   OpenShiftIdentityProviderTest.preTest:81 » IllegalState Problem setting up ssl
[ERROR]   OpenShiftIdentityProviderTest.preTest:81 » IllegalState Problem setting up ssl
[ERROR]   OpenShiftIdentityProviderTest.preTest:81 » IllegalState Problem setting up ssl
[INFO] 
[ERROR] Tests run: 5, Failures: 0, Errors: 4, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.984 s
[INFO] Finished at: 2019-09-01T10:04:02-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project sonar-auth-openshift-plugin: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/dphillips/Documents/RedHat/Workspace/sonar-auth-openshift-1/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Are there extra instructions needed to successfully build and test? If so, we should add a "Building" section to the README.

**Comment by InfoSec812** [comment]
Weird... It builds fine on [TravisCI](https://travis-ci.com/InfoSec812/sonar-auth-openshift-1/builds/125353895)... I had Java 12 enabled on my local machine and then switched to Java 8 (OpenJDK) and it made no difference.

**Comment by mcanoy** [comment]
Do you want to try and run your build/test again? The latest merge should give a better error message (hopefully) when it fails to init. I suspect a lack of kubeconfig but I'm not sure. There may need to be some env vars added during test.

**Comment by InfoSec812** [comment]
Works now! Thanks @mcanoy
